### ISSUE TITLE
HAL development

### ISSUE THREAD

**Issue by JinZhuXing** [lbule/Goodix_Fingerprint#1]
Hello,
I want to ask you about the HAL development.
I found a libgf_hal.so file at your repository.
Can you tell me the development guide or source code about this library?
I want to make my own libary for it.
Thank you.

**Comment by alexstsv2** [comment]
These are proprietary libraries, we do not have the source code. The library itself is located in the firmware miui /vendor/lib(64) .
and these libraries and others are taken from the miui firmware as is, for example
https://github.com/marble-development/android_device_xiaomi_marble/blob/ee39a2d7ae32e2a84f38f8b15a1ca5eadfff1e5e/proprietary-files.txt#L1682
and this hidl https://github.com/Evolution-X/hardware_xiaomi/tree/udc/hidl/biometrics/fingerprint

**Comment by JinZhuXing** [comment]
Thank you.
